web:
  build: .
  dockerfile: website/Dockerfile
  ports:
  - "4000:8080"
  links:
  - stylechecker-service
  volumes:
  - ./stylechecker/src/main/proto/:/usr/src/app/stylechecker/src/main/proto/:rw
  - ./website/:/usr/src/app/website:rw
  environment:
  - NODE_ENV=development
  command: >
    sh -c '
      if test -d node_modules; 
      then 
        echo node_modules_exists ; 
      else 
        cp -a /tmp/node_modules /usr/src/app/website; 
      fi && 
      npm install && 
      /usr/local/bin/node ./index.js
    '
stylechecker-service:
  build: ./stylechecker
  ports:
  - "50051:50051"
