apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    role: api-server
    usage: prod
spec:
  ports:
  - port: 50052
    targetPort: 50052
  selector:
    role: api-server
    usage: prod