apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    role: frontend
    usage: prod
spec:
  replicas: 3
  selector:
    role: frontend
    usage: prod
  template:
    metadata:
      labels:
        role: frontend
        usage: prod
    spec:
      containers:
      - name: frontend-nginx
        image: andyccs/some-frontend-name:0.2.0
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 50053