apiVersion: v1
kind: Service
metadata:
  name: stylechecker-service
  labels:
    role: stylechecker-service
    usage: prod
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    role: stylechecker-service
    usage: prod